apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/service
  - ./serviceaccount.yaml

patches:
  - path: ./container-version.yaml
    target:
      kind: HelmRelease
      name: service
  - path: ./metadata-instance.yaml
    target:
      kind: HelmRelease
      name: service
  - path: ./service-annotation-okteto-ingress.yaml
    target:
      kind: HelmRelease
      name: service
  - path: ./secretproviderclass.yaml
    target:
      kind: SecretProviderClass
      name: service
  - path: ./issuer.yaml
    target:
      kind: Issuer
      name: service
  - path: ./ingress.yaml
    target:
      kind: Ingress
      name: wizard-test-service
  # PrometheusRule is not supported in Okteto
  - target:
      kind: PrometheusRule
    patch: |
      $patch: delete
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        name: DOES NOT MATTER
  # Explicit Ingress (and so Issuer) is not needed in Okteto. Ingress is created automatically when service is exposed
  - target:
      kind: Ingress
    patch: |
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: DOES NOT MATTER
  - target:
      kind: Issuer
    patch: |
      $patch: delete
      apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
        name: DOES NOT MATTER

commonLabels:
  dev.okteto.com/deployed-by: wizard-test
