# This service account is normally created during the infra
# deployment. In deployments to Okteto, we need to create
# it ourselves. The '$xxx' tokens are replaced at run time
# with environment variables during the 'okteto deploy'
# executions.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service
  annotations:
    azure.workload.identity/client-id: $OKTETO_EXTERNAL_AMI_CLIENTID