services:
  tests:
    build:
      context: .
      target: build
    env_file:
      - ./variables.env
    command: >
      sh -c 'for dir in tests/*UnitTests; do
      dotnet test $$dir
      --collect:"XPlat Code Coverage"
      --results-directory "./artifacts/tests/output"
      --configuration Debug
      --logger "trx"
      ;done'
    volumes:
      - "./artifacts/tests/output:/src/artifacts/tests/output"
