---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: service
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: ''
    keyvaultName: ''
    tenantID: fc1f6b68-bb68-429e-8230-5fe7bb899d52
    cloudName: AzurePublicCloud
    objects: |
      array:
        - |
          objectName: test-secret
          objectAlias: test-secret
          objectType: secret
  secretObjects:
  - data:
    -
      key: test-secret
      objectName: test-secret
    secretName: service
    type: Opaque
