apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base/service

namespace: wizard-test

patches:
  - path: ./container-version.yaml
    target:
      kind: HelmRelease
      name: service
  - path: ./metadata-instance.yaml
    target:
      kind: HelmRelease
      name: service
  - path: ./secretproviderclass.yaml
    target:
      kind: SecretProviderClass
      name: service
  - path: ./issuer.yaml
    target:
      kind: Issuer
      name: service
  - path: ./ingress.yaml
    target:
      kind: Ingress
      name: wizard-test-service
