# NOTE: this workload has an issue - it can't push a change in `.github/workflows` files.
# It fails with `refusing to allow a GitHub App to create or update workflow `.github/workflows/dev.yaml` without `workflows` permission`.
name: initialize-zero

on:
  workflow_dispatch:

env:
  IACCLI_VERSION: ${{ inputs.tool-version || 'latest'}}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'cicddemo' # we need env to read secrets.ENV_DEPLOY_CLIENTID. TODO: solve this
    permissions:
      contents: write
      packages: write
      id-token: write
      issues: read
      checks: write
      actions: read
      deployments: write
      discussions: read
      pages: read
      pull-requests: read
      repository-projects: read
      statuses: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ST_INFRA_PLATFORM_APP_ID }}
          private-key: ${{ secrets.ST_INFRA_PLATFORM_APP_SECRET }}
          owner: ${{ github.repository_owner }}

      - name: Install IAC
        uses: servicetitan/infra-iac-poc/actions/install-iac@master
        with:
          subscription-id: ${{ vars.ENV_SUBSCRIPTIONID }}
          client-id: ${{ secrets.ENV_DEPLOY_CLIENTID }}
          tool-version: ${{ env.IACCLI_VERSION }}
          gh-token: ${{ steps.app-token.outputs.token }}
          skip-update-manifest: true

      - name: set git config
        run: |
          git config user.email "iac@servicetitan.com"
          git config user.name "iac"

      - name: Init iac files
        run: iac init --force
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: check for changes
        id: git_status_init_iac
        run: echo "changes=$(git status --porcelain)" >> "$GITHUB_OUTPUT"
      - name: stage changed files
        if: steps.git_status_init_iac.outputs.changes != ''
        run: git add .
      - name: commit changed files
        if: steps.git_status_init_iac.outputs.changes != ''
        run: git commit -m "[no ci] Initialized iac files"

      - name: push code to origin
        env:
          GITHUB_TOKEN: ${{ secrets.IVTEST_WRKFLW_PAT }}
        run: git push https://x-access-token:${{ secrets.IVTEST_WRKFLW_PAT }}@github.com/${{ github.repository }}.git
